### ISSUE TITLE
Found multiple users in search base

### ISSUE THREAD

**Issue by stefanbesler** [gocd/gocd-ldap-authentication-plugin#41]
I am trying to set LDAP configuration up with the help of our admin, I can connect to the LDAP server (the Ok Test in GoCD says that everything is alright), but when I try to connect with a username, I always get this output in the logfile and the user can't authenticate.

```
2018-07-13 12:20:58,982 ERROR [qtp1895219288-37] LdapPlugin:128 - [Authenticate] Failed to authenticate user <username> on ldap://****.****:****. 
java.lang.RuntimeException: Found multiple users in search base `OU=***,OU=users,OU=****,DC=****,DC=****,DC=com` with username `<username>`. 
	at cd.go.framework.ldap.Ldap.authenticate(Ldap.java:61)
```

(I blanked out the servername etc.)

Since the Manager DN and URL seem fine (as confirmed by the GoCD "Ok Test"), I only post the other relevant configuration

<property>
    <key>UserLoginFilter</key>
    <value>(userPrincipalName={0})</value>
</property>

The searchbase matches the Manager DN's - without the CN of the manager. Any ideas?

**Comment by bdpiparva** [comment]
@stefanbesler -- please can you share the output of(after removing sensetive info) `ldapsearch -x -H ldap://ldap-hostname:389/ -b "<search-base>" -D "Manager_DN" -W "userPrincipalName =USERNAME"`.

**Comment by stefanbesler** [comment]
hi @bdpiparva, here the result that i got

```
> ldapsearch -x -H ldap://***.com:389 -b "OU=***,OU=users,OU=***,DC=***,DC=***,DC=com" -D "CN=Besler Stefan,OU=***,OU=users,OU=***,DC=***,DC=***,DC=com" -W "userPrincipalName=testuser"
Enter LDAP Password: ***.
ldap_connect_to_host: TCP ***.com:389
ldap_new_socket: 604
ldap_prepare_socket: 604
ldap_connect_to_host: Trying ***.***.***.***:389
ldap_pvt_connect: fd: 604 tm: -1 async: 0
attempting to connect:
connect success
# extended LDIF
#
# LDAPv3
# base <OU=***,OU=users,OU=***,DC=***,DC=***,DC=com> with scope subtree
# filter: userPrincipalName=testuser
# requesting: ALL
#

# search result
search: 2
result: 10 Referral
text: 0000202B: RefErr: DSID-0310074A, data 0, 1 access points
        ref 1: '***.***.com'

ref: ldap://***.***.com/OU=***,OU=users,OU=***,DC=***,DC=***,DC=com

# numResponses: 1
```

**Comment by stefanbesler** [comment]
It was a config error on my side, I used the wrong subdomain.
Thanks for helping me out with ldapsearch that way I could figure out the problem on my own. But probably the error message should be something like "no result found" instead of "multiple users found"

**Comment by bdpiparva** [comment]
@stefanbesler -- Thanks for reporting this. I am not able to replicate the issue locally. Please, can you provide more information about how did you get "multiple users found" in the error message?

#### Steps I took to replicate the issue
1. I am using this `bdpiprava/ldap-server` as ldap server. 
  `docker run -d -p 10389:10389 bdpiprava/ldap-server`

Above image has a couple of users in it.

```
ManagerDN: uid=admin,ou=system
Password    : secret
```

```
username: bford
Password: bob
```

2. Ldap configuration
```xml
<authConfig id="demo" pluginId="cd.go.authentication.ldap">
  <property>
    <key>Url</key>
    <value>ldap://localhost:10389</value>
  </property>
  <property>
    <key>SearchBases</key>
    <value>ou=system</value>
  </property>
  <property>
    <key>ManagerDN</key>
    <value>uid=admin,ou=system</value>
  </property>
  <property>
    <key>Password</key>
    <value>secret</value>
  </property>
  <property>
    <key>UserSearchFilter</key>
    <value />
  </property>
  <property>
    <key>UserLoginFilter</key>
    <value>(uid={0})</value>
  </property>
  <property>
    <key>DisplayNameAttribute</key>
    <value />
  </property>
  <property>
    <key>EmailAttribute</key>
    <value />
  </property>
</authConfig>
```

Using the above config, tried login using some random username which does not exist in LDAP server it gives me following error.
```
2018-07-16 16:25:34,983 ERROR [qtp910599202-16] LdapPlugin:128 - [Authenticate] Failed to authenticate user test on ldap://localhost:10389.
java.lang.RuntimeException: User test does not exist in ldap://localhost:10389
```

**Comment by HenryTheSir** [comment]
Hi guys, I can reproduce this issue.

Output of ldapsearch is attached, tested with newest stable and beta release:

`ldapsearch -x  -H ldap://ldap..de:389 -b "dc=,dc=de" -D "cn=,ou=GoCD,ou=Services,ou=Ressourcen,ou=,dc=,dc=de" -W "userPrincipalName=ddasdfe345adsf"
Enter LDAP Password:
# extended LDIF
#
# LDAPv3
# base <dc=,dc=de> with scope subtree
# filter: userPrincipalName=ddasdfe345adsf
# requesting: ALL
#

# search reference
ref: ldap://ForestDnsZones..de/DC=ForestDnsZones,DC=,DC=de

# search reference
ref: ldap://DomainDnsZones..de/DC=DomainDnsZones,DC=,DC=de

# search reference
ref: ldap://.de/CN=Configuration,DC=,DC=de

# search result
search: 2
result: 0 Success

# numResponses: 4
# numReferences: 3
`
`2018-08-14 16:32:00,699 ERROR [qtp809762318-24] LdapPlugin:128 - [Authenticate] Failed to authenticate user d on ldap://ldap..de:389.
java.lang.RuntimeException: Found multiple users in search base `dc=,dc=de` with username `d`.
        at cd.go.framework.ldap.Ldap.authenticate(Ldap.java:61)
        at cd.go.authentication.ldap.LdapAuthenticator.authenticateWithAuthConfig(LdapAuthenticator.java:58)
        at cd.go.authentication.ldap.LdapAuthenticator.authenticate(LdapAuthenticator.java:44)
        at cd.go.authentication.ldap.executor.UserAuthenticationExecutor.execute(UserAuthenticationExecutor.java:50)
        at cd.go.authentication.ldap.LdapPlugin.handle(LdapPlugin.java:69)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:143)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:225)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:202)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:140)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
        at com.thoughtworks.go.plugin.access.authorization.AuthorizationExtension.authenticateUser(AuthorizationExtension.java:122)
        at com.thoughtworks.go.server.newsecurity.providers.PasswordBasedPluginAuthenticationProvider.authenticateWithExtension(PasswordBasedPluginAuthenticationProvider.java:78)
        at com.thoughtworks.go.server.newsecurity.providers.PasswordBasedPluginAuthenticationProvider.authenticateWithExtension(PasswordBasedPluginAuthenticationProvider.java:39)
        at com.thoughtworks.go.server.newsecurity.providers.AbstractPluginAuthenticationProvider.authenticateUser(AbstractPluginAuthenticationProvider.java:117)
        at com.thoughtworks.go.server.newsecurity.providers.AbstractPluginAuthenticationProvider.authenticate(AbstractPluginAuthenticationProvider.java:84)
        at com.thoughtworks.go.server.newsecurity.controllers.AuthenticationController.performLogin(AuthenticationController.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:181)
        at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:440)
        at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:428)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at com.thoughtworks.go.server.web.FlashLoadingFilter.doFilterInternal(FlashLoadingFilter.java:39)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at com.thoughtworks.go.server.newsecurity.filters.DenyIfRefererIsNotFilesFilter.doFilterInternal(DenyIfRefererIsNotFilesFilter.java:53)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at com.thoughtworks.go.server.newsecurity.filters.AllowAllAccessFilter.doFilterInternal(AllowAllAccessFilter.java:34)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at com.thoughtworks.go.server.newsecurity.filters.AbstractUserEnabledCheckFilter.doFilterInternal(AbstractUserEnabledCheckFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at com.thoughtworks.go.server.newsecurity.filters.ThreadLocalUserFilter.doFilterInternal(ThreadLocalUserFilter.java:42)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at com.thoughtworks.go.server.newsecurity.filters.AssumeAnonymousUserFilter.doFilterInternal(AssumeAnonymousUserFilter.java:65)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at com.thoughtworks.go.server.newsecurity.filters.AlwaysCreateSessionFilter.doFilterInternal(AlwaysCreateSessionFilter.java:41)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at com.thoughtworks.go.server.newsecurity.filters.ModeAwareFilter.doFilter(ModeAwareFilter.java:53)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at com.thoughtworks.go.server.newsecurity.filterchains.MainFilterChain.doFilter(MainFilterChain.java:76)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at com.thoughtworks.go.server.web.BackupFilter.doFilter(BackupFilter.java:86)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at com.thoughtworks.go.server.web.DefaultHeadersFilter.doFilter(DefaultHeadersFilter.java:36)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Thread.java:748)
`

Before upgrading to latest release this config worked quite fine

King regards

**Comment by HenryTheSir** [comment]
After adding an OU to the search base the Authentication works again and the result of ldapsearch is different. There are now no querys against 

search reference
ref: ldap://ForestDnsZones..de/DC=ForestDnsZones,DC=,DC=de

search reference
ref: ldap://DomainDnsZones..de/DC=DomainDnsZones,DC=,DC=de
